name: Branch Protection - Main

'on':
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-source-branch:
    name: Validate PR Source Branch
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from develop branch
        uses: actions/github-script@v7
        with:
          script: |
            const prHeadRef = context.payload.pull_request.head.ref;
            const baseBranch = 'develop';

            console.log(`PR head branch: ${prHeadRef}`);
            console.log(`Expected base branch: ${baseBranch}`);

            if (prHeadRef !== baseBranch) {
              const message = `❌ **Branch Protection Policy Violation**

              Pull requests to \`main\` branch are only allowed from \`${baseBranch}\` branch.

              **Current PR source:** \`${prHeadRef}\`
              **Required source:** \`${baseBranch}\`

              Please close this PR and create a new one from the \`${baseBranch}\` branch.
              `;

              // Comment on the PR
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });

              const errorMsg = `Pull request to main must come from ` +
                `${baseBranch} branch. Current source: ${prHeadRef}`;
              core.setFailed(errorMsg);
            } else {
              const message = `✅ **Branch Protection Check Passed**

              This pull request correctly originates from the \`${baseBranch}\` branch.
              `;

              // Comment on the PR
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });

              console.log('✅ Branch protection check passed');
            }
