name: PR - Quality Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  affected-tests:
    name: Test Affected Projects
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ github.event.pull_request.base.ref }}

      - name: Run tests for affected projects
        run: npx nx affected -t test --parallel=3 --coverage
        continue-on-error: false

      - name: Build affected projects
        run: npx nx affected -t build --parallel=3

      - name: Comment PR with test results
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const testResults = '✅ All tests passed successfully!';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Test Results\n\n${testResults}\n\n*Automated comment by CI pipeline*`
            });

      - name: Comment PR with failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const failureMessage = '❌ Tests failed. Please check the workflow logs for details.';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Test Results\n\n${failureMessage}\n\n*Automated comment by CI pipeline*`
            });

  security-check:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Run security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Check for vulnerabilities
        run: |
          echo "Checking dependencies for known vulnerabilities..."
          npm audit --json > audit-results.json || true
          cat audit-results.json
