name: Validate PR Source Branch

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, edited]

permissions:
  pull-requests: write
  contents: read

jobs:
  validate-source-branch:
    name: Validate Source Branch
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if PR is from develop branch
        uses: actions/github-script@v7
        with:
          script: |
            const sourceBranch = context.payload.pull_request.head.ref;
            const allowedBranch = 'develop';
            
            console.log(`Source branch: ${sourceBranch}`);
            console.log(`Target branch: ${context.payload.pull_request.base.ref}`);
            
            if (sourceBranch !== allowedBranch) {
              const message = `❌ **Invalid Source Branch**
              
              Pull requests to \`main\` branch must originate from the \`${allowedBranch}\` branch only.
              
              **Current source branch:** \`${sourceBranch}\`
              **Required source branch:** \`${allowedBranch}\`
              
              Please close this PR and create a new one from the \`${allowedBranch}\` branch.`;
              
              // Comment on the PR
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
              
              core.setFailed(`PR source branch must be '${allowedBranch}' but got '${sourceBranch}'`);
            } else {
              console.log('✅ Source branch validation passed');
              
              const message = `✅ **Source Branch Validation Passed**
              
              This pull request correctly originates from the \`${allowedBranch}\` branch.`;
              
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            }
